version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 7
  build:
    commands:
      - echo Nothing to do yet

artifacts:
  files:
    - index.html
    - favicon.ico
    - Navid-Haghighi-Resume.pdf
    - styles/*
    - images/*
